INSERT INTO `prices` (`id`, `end_date`, `price`, `start_date`, `type`)
VALUES (1, NULL, 60, NULL, 'Luxe'),
       (2, NULL, 100, NULL, 'VIP'),
       (3, NULL, 8, NULL, 'Au fond'),
       (4, NULL, 55, NULL, 'Carré'),
       (5, NULL, 20, NULL, 'Standard'),
       (6, NULL, 29, NULL, 'Adulte'),
       (7, NULL, 26, NULL, 'Enfant'),
       (8, NULL, 32, NULL, 'Balcons'),
       (9, NULL, 45, NULL, 'Parterre'),
       (10, NULL, 49.5, NULL, 'Fauteuils'),
       (11, NULL, 45, NULL, 'Corbeilles'),
       (12, NULL, 39, NULL, 'Balcons'),
       (13, NULL, 38, NULL, 'Catégorie 1'),
       (14, NULL, 35, NULL, 'Catégorie 2'),
       (15, NULL, 29, NULL, 'Catégorie 3'),
       (16, NULL, 49, NULL, 'Balcons'),
       (17, NULL, 60, NULL, 'Tribunes'),
       (18, NULL, 80, NULL, 'Parterres'),
       (19, NULL, 119, NULL, 'Loges'),
       (20, NULL, 49, NULL, 'Parterres'),
       (21, NULL, 60, NULL, 'Balcons'),
       (22, NULL, 49, NULL, 'Corbeilles'),
       (23, NULL, 42, NULL, 'Parterres'),
       (24, NULL, 38, NULL, 'Balcons'),
       (25, NULL, 34, NULL, 'Corbeilles');