INSERT INTO `artists` (`id`, `firstname`, `lastname`,`troupe_id`)
VALUES (1, 'Pascale', 'Louange',1),
       (2, 'Thomas', 'Hardmeier',2),
       (3, 'Caroline', 'Grastilleur',3),
       (4, 'Antoine', 'Le cointe',4),
       (5, 'Aurélien', 'Bianco',1),
       (6, 'Eric', 'Théobald',2),
       (7, 'Richar', 'Berry',3),
       (8, 'Anthony ', 'Gargiulo',4),
       (9, 'Alessandro', 'Caprini',1),
       (10, 'Charline', 'Piielquin',2),
       (11, 'Teddy', 'Cauvin',3),
       (12, 'David', 'Castello-Lopes',4),
       (13, 'Romane', 'Frayssinet',1),
       (14, 'Olivier', 'De Benoist',2),
       (15, 'Paul-Marie', 'Debrie',3),
       (16, 'Jérôme', 'Daran',4),
       (17, 'Ilyes', 'Djadel',1),
       (18, 'Véronique', 'Gallo',2),
       (19, 'Amandine', 'Letawe',3),
       (20, 'Jean', 'Lambert',4),
       (21, 'Jeremy', 'Ferrari',1),
       (22, 'Arnaud', 'Tsamere',2),
       (23, 'Baptiste', 'Lecaplain',3),
       (24, 'Dany', 'Boon',4),
       (25, 'Isabelle', 'Nanty',1),
       (26, 'Véronique', 'Guéret',2),
       (27, 'Laura', 'Laune',3);