# INSERT INTO `artists` (`id`, `firstname`, `lastname`, `troupe_id`)
# VALUES (1, 'Pascale', 'Louange'),
#        (2, 'Thomas', 'Hardmeier'),
#        (3, 'Caroline', 'Grastilleur'),
#        (4, 'Antoine', 'Le cointe'),
#        (5, 'Aurélien', 'Bianco'),
#        (6, 'Eric', 'Théobald'),
#        (7, 'Richar', 'Berry'),
#        (8, 'Anthony ', 'Gargiulo'),
#        (9, 'Alessandro', 'Caprini'),
#        (10, 'Charline', 'Piielquin'),
#        (11, 'Teddy', 'Cauvin'),
#        (12, 'David', 'Castello-Lopes'),
#        (13, 'Romane', 'Frayssinet'),
#        (14, 'Olivier', 'De Benoist'),
#        (15, 'Paul-Marie', 'Debrie'),
#        (16, 'Jérôme', 'Daran'),
#        (17, 'Ilyes', 'Djadel'),
#        (18, 'Véronique', 'Gallo'),
#        (19, 'Amandine', 'Letawe'),
#        (20, 'Jean', 'Lambert'),
#        (21, 'Jeremy', 'Ferrari'),
#        (22, 'Arnaud', 'Tsamere'),
#        (23, 'Baptiste', 'Lecaplain'),
#        (24, 'Dany', 'Boon'),
#        (25, 'Isabelle', 'Nanty'),
#        (26, 'Véronique', 'Guéret'),
#        (27, 'Laura', 'Laune');

INSERT INTO artists (id, firstname, lastname, troupe_id) VALUES
                                                             (1, 'Pascale', 'Louange',        1),
                                                             (2, 'Thomas',  'Hardmeier',       2),
                                                             (3, 'Caroline','Grastilleur',     2),
                                                             (4, 'Antoine', 'Le cointe',       2),
                                                             (5, 'Aurélien','Bianco',          3),
                                                             (6, 'Eric',    'Théobald',        4),
                                                             (7, 'Richar',  'Berry',           4),
                                                             (8, 'Anthony', 'Gargiulo',        5),
                                                             (9, 'Alessandro','Caprini',       5),
                                                             (10,'Charline','Piielquin',       6),
                                                             (11,'Teddy',   'Cauvin',          6),
                                                             (12,'David',   'Castello-Lopes',  7),
                                                             (13,'Romane',  'Frayssinet',      7),
                                                             (14,'Olivier', 'De Benoist',      8),
                                                             (15,'Paul-Marie','Debrie',        8),
                                                             (16,'Jérôme',  'Daran',           9),
                                                             (17,'Ilyes',   'Djadel',          9),
                                                             (18,'Véronique','Gallo',         10),
                                                             (19,'Amandine','Letawe',         10),
                                                             (20,'Jean',     'Lambert',       11),
                                                             (21,'Jeremy',   'Ferrari',       11),
                                                             (22,'Arnaud',   'Tsamere',       12),
                                                             (23,'Baptiste', 'Lecaplain',     12),
                                                             (24,'Dany',     'Boon',          13),
                                                             (25,'Isabelle','Nanty',         14),
                                                             (26,'Véronique','Guéret',        14),
                                                             (27,'Laura',    'Laune',         14);