INSERT INTO `artists` (`id`, `firstname`, `lastname`)
VALUES (1, 'Pascale', 'Louange'),
       (2, 'Thomas', 'Hardmeier'),
       (3, 'Caroline', 'Grastilleur'),
       (4, 'Antoine', 'Le cointe'),
       (5, 'Aurélien', 'Bianco'),
       (6, 'Eric', 'Théobald'),
       (7, 'Richar', 'Berry'),
       (8, 'Anthony ', 'Gargiulo'),
       (9, 'Alessandro', 'Caprini'),
       (10, 'Charline', 'Piielquin'),
       (11, 'Teddy', 'Cauvin'),
       (12, 'David', 'Castello-Lopes'),
       (13, 'Romane', 'Frayssinet'),
       (14, 'Olivier', 'De Benoist'),
       (15, 'Paul-Marie', 'Debrie'),
       (16, 'Jérôme', 'Daran'),
       (17, 'Ilyes', 'Djadel'),
       (18, 'Véronique', 'Gallo'),
       (19, 'Amandine', 'Letawe'),
       (20, 'Jean', 'Lambert'),
       (21, 'Jeremy', 'Ferrari'),
       (22, 'Arnaud', 'Tsamere'),
       (23, 'Baptiste', 'Lecaplain'),
       (24, 'Dany', 'Boon'),
       (25, 'Isabelle', 'Nanty'),
       (26, 'Véronique', 'Guéret'),
       (27, 'Laura', 'Laune');